# Generated by Django 4.2.4 on 2023-08-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='n/a', max_length=256),
        ),
    ]
