# Generated by Django 4.2.4 on 2023-08-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_alter_book_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_10', models.CharField(blank=True, max_length=10)),
                ('isbn_13', models.CharField(blank=True, max_length=13)),
            ],
        ),
    ]
